import { jsPDF } from 'jspdf';
import type { FilledFormData, FormDefinition, Language } from '@/types';

/**
 * Generate a PDF of the filled form and trigger a download.
 */
export function generateFormPDF(
  form: FormDefinition,
  filledData: FilledFormData,
  lang: Language,
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 20;
  const contentWidth = pageWidth - marginX * 2;
  let y = 20;

  // Header bar
  doc.setFillColor(255, 107, 26); // saffron
  doc.rect(0, 0, pageWidth, 8, 'F');

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text(form.name[lang], marginX, y + 8);
  y += 16;

  // Subtitle
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const subtitles: Record<Language, string> = {
    en: 'Government of India — Form Filled by BharoAI',
    hi: 'भारत सरकार — BharoAI द्वारा भरा गया फॉर्म',
    mr: 'भारत सरकार — BharoAI द्वारे भरलेला फॉर्म',
  };
  doc.text(subtitles[lang], marginX, y);
  y += 6;

  // Separator line
  doc.setDrawColor(255, 107, 26);
  doc.setLineWidth(0.5);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 10;

  // Form fields
  doc.setFontSize(11);
  for (const field of form.fields) {
    const label = field.label[lang];
    const value = filledData.values[field.key] || '-';

    // Check if we need a new page
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    // Label
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${label}:`, marginX, y);

    // Value (wrap text)
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(20, 20, 20);
    const labelWidth = 50;
    const valueLines = doc.splitTextToSize(value, contentWidth - labelWidth);
    doc.text(valueLines, marginX + labelWidth, y);

    y += Math.max(7, valueLines.length * 5 + 3);
  }

  // Footer
  y = Math.max(y + 10, 270);
  if (y > 280) {
    doc.addPage();
    y = 20;
  }

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 6;

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const generatedText: Record<Language, string> = {
    en: `Generated by BharoAI on ${new Date().toLocaleDateString('en-IN')}`,
    hi: `BharoAI द्वारा ${new Date().toLocaleDateString('hi-IN')} को तैयार किया गया`,
    mr: `BharoAI द्वारे ${new Date().toLocaleDateString('mr-IN')} रोजी तयार केले`,
  };
  doc.text(generatedText[lang], marginX, y);

  // Footer bar
  doc.setFillColor(19, 136, 8); // ashok green
  doc.rect(0, doc.internal.pageSize.getHeight() - 4, pageWidth, 4, 'F');

  // Download
  const filename = `${form.id}_form_${Date.now()}.pdf`;
  doc.save(filename);
}
